import 'package:course_project/models/postModel.dart';

List<Postmodel> Places = [
  Postmodel(
    id: "post1",
    userId: "user1",
    approval: true,
    placeName: "Al Qurum Park",
    location: "23.5917° N, 58.4447° E",
    description: "A beautiful public park located in Muscat with green spaces and walking trails.",
    rating: 5,
    governorate: "Muscat",
    placeType: "Park",
    image: "lib/assets/oman1.jpeg",
  ),
  Postmodel(
    id: "post2",
    userId: "user2",
    approval: false,
    placeName: "Muttrah Souq",
    location: "23.6159° N, 58.5933° E",
    description: "One of the oldest markets in Oman offering traditional goods and spices.",
    rating: 4,
    governorate: "Muscat",
    placeType: "Market",
    image: "lib/assets/oman2.webp",
  ),
  Postmodel(
    id: "post3",
    userId: "user3",
    approval: true,
    placeName: "Jebel Akhdar",
    location: "23.0680° N, 57.6662° E",
    description: "Mountainous area famous for hiking, scenic views, and terraced farms.",
    rating: 5,
    governorate: "Ad Dakhiliyah",
    placeType: "Mountain",
    image: "lib/assets/oman3.jpeg",
  ),
  Postmodel(
    id: "post4",
    userId: "user4",
    approval: true,
    placeName: "Wadi Shab",
    location: "22.8284° N, 59.2386° E",
    description: "A popular outdoor spot with swimming pools, waterfalls, and caves.",
    rating: 5,
    governorate: "Ash Sharqiyah South",
    placeType: "Wadi",
    image: "lib/assets/oman1.jpeg",
  ),
  Postmodel(
    id: "post5",
    userId: "user5",
    approval: true,
    placeName: "Sultan Qaboos Grand Mosque",
    location: "23.5859° N, 58.3959° E",
    description: "One of the largest mosques in the world, known for its stunning architecture.",
    rating: 5,
    governorate: "Muscat",
    placeType: "Mosque",
    image: "lib/assets/oman1.jpeg",
  ),
  Postmodel(
    id: "post6",
    userId: "user6",
    approval: true,
    placeName: "Nizwa Fort",
    location: "22.9333° N, 57.5333° E",
    description: "A historic fort with a large cylindrical tower, museum, and panoramic views.",
    rating: 4,
    governorate: "Ad Dakhiliyah",
    placeType: "Fort",
    image: "lib/assets/oman1.jpeg",
  ),
  Postmodel(
    id: "post7",
    userId: "user7",
    approval: true,
    placeName: "Ras Al Jinz",
    location: "22.4700° N, 59.8333° E",
    description: "A turtle reserve where you can watch sea turtles nesting on the beach.",
    rating: 5,
    governorate: "Ash Sharqiyah South",
    placeType: "Nature Reserve",
    image: "lib/assets/oman1.jpeg",
  ),
  Postmodel(
    id: "post8",
    userId: "user8",
    approval: true,
    placeName: "Bimmah Sinkhole",
    location: "23.0122° N, 59.0702° E",
    description: "A natural limestone crater with turquoise water, great for swimming.",
    rating: 5,
    governorate: "Muscat",
    placeType: "Sinkhole",
    image: "lib/assets/oman2.jpeg",
  ),
  Postmodel(
    id: "post9",
    userId: "user9",
    approval: true,
    placeName: "Salalah Beaches",
    location: "17.0190° N, 54.0897° E",
    description: "White sandy beaches with palm trees and clear blue water in southern Oman.",
    rating: 4,
    governorate: "Dhofar",
    placeType: "Beach",
    image: "lib/assets/oman2.jpeg",
  ),
  Postmodel(
    id: "post10",
    userId: "user10",
    approval: true,
    placeName: "Al Hoota Cave",
    location: "23.0583° N, 57.3714° E",
    description: "A cave system with underground lakes and stalactites accessible by guided tours.",
    rating: 4,
    governorate: "Ad Dakhiliyah",
    placeType: "Cave",
    image: "lib/assets/oman1.jpeg",
  ),
];
