// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8kesTqo4tBKKeunMnYPhUt8UYcOyPpo',
    appId: '1:353782118586:android:76b3d361f8e0087f8a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb125DrrxWgStm-cODCN6Bb5zU0sr8R4w',
    appId: '1:353782118586:ios:bae22eb86d874a6a8a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.firebasestorage.app',
    iosBundleId: 'com.example.courseProject',
  );

}